---
  - name: installing and launching filebeat
    hosts: elk
    become: yes
    tasks:

      - name: download filebeat deb
        command: curl -L -O artifacts.elastic.co/downloads/bea>

      - name: install filebeat deb
        command: dpkg -i filebeat-7.4.0-amd64.deb

      - name: drop in filebeat.yml
        copy:
          src: /etc/ansible/files/filebeat-config.yml
          dest: /etc/filebeat/filebeat.yml

      - name: enable and configure system module
        command: sudo filebeat modules enable system

      - name: setup filebeat
        command: filebeat setup

      - name: start filebeat service
        command: service filebeat start

      - name: enable service filebeat on boot
        systemd:
          name: enable filebeat service
          enabled: yes
