---
  - name: Install Elk Playbook
    hosts: elk
    become: true
    tasks:

      - name: updating vm.max_map_count
        sysctl:
          name: vm.max_map_count
          value: 262144
          reload: yes
          sysctl_file: "/etc/sysctl.conf"

      - name: Install Docker
        apt:
          update_cache: yes
          name: docker.io
          state: present

      - name: Install Python
        pip:
          name: docker
          state: present

      - name: download and launch a docker web container
        docker_container:
          name: elk
          image: sebp/elk:761
          state: started
          restart_policy: always
          published_ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044
